version: '3'
services:
  db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 --settings=myproject.settings"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
  
volumes:
  db_data:

